module.exports = {
  process: function () {
    return {
      code: 'module.exports = {"src":"/_next/static/image/public/me.f3d4c48c95435f48078376d6250db234.jpeg","height":1080,"width":718,"blurDataURL":"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/sBCgoKCgoKCwwMCw8QDhAPFhQTExQWIhgaGBoYIjMgJSAgJSAzLTcsKSw3LVFAODhAUV5PSk9ecWVlcY+Ij7u7+//CABEIAAgABQMBIgACEQEDEQH/xAAUAAEAAAAAAAAAAAAAAAAAAAAG/9oACAEBAAAAADf/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/9oACAECEAAAAD//xAAUAQEAAAAAAAAAAAAAAAAAAAAC/9oACAEDEAAAAH//xAAcEAACAgIDAAAAAAAAAAAAAAABAgMEABIRUmH/2gAIAQEAAT8A2oUVihFffWNQSqcEns3pz//EABYRAAMAAAAAAAAAAAAAAAAAAAABEv/aAAgBAgEBPwCUf//EABURAQEAAAAAAAAAAAAAAAAAAAAR/9oACAEDAQE/AK//2Q=="}'
    }
  }
}
